#!/bin/bash

shopt -s nullglob

EXTERN_PROB_PATH=../cg2_2014_demo/prob_7
EXTERN_COMMON_PATH=../cg2_2014_demo/common

HOSTTYPE=${HOSTTYPE} LANG=en_US.US-ASCII EXTERN_COMMON_PATH=${EXTERN_COMMON_PATH} EXTERN_PROB_PATH=${EXTERN_PROB_PATH} xcrun make $@
